version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./:/var/www
      - ./logs/nginx:/var/log/nginx
    links:
      - php
  php:
    build: ./images/php
    volumes:
      - ./:/var/www